version: '3.4'

x-common-env-variables: &common-env-variables
  STAGE: development-docker

services:
  todo-nuxt:
    image: rodarte/yc-nuxt3-todo-app-dev:f4c0ddf
    environment:
      <<: *common-env-variables
      PORT: 3000
      HMR_PORT: 3001
      HOST: 0.0.0.0
      NUXT_PUBLIC_STAGE: development-docker
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      # nuxt source code (pages, components, store, etc.)
      - ./todo-nuxt3/.nuxt:/node/.nuxt
      - ./todo-nuxt3/src:/node/src
      # config files
      - ./todo-nuxt3/nuxt.config.ts:/node/nuxt.config.ts
      - ./todo-nuxt3/package.json:/node/package.json
      - ./todo-nuxt3/tailwind.config.js:/node/tailwind.config.js
      - ./todo-nuxt3/tsconfig.json:/node/tsconfig.json
      - ./todo-nuxt3/vite.config.ts:/node/vite.config.ts
