version: '3.4'

x-common-env-variables: &common-env-variables
  STAGE: development-docker

services:
  todo-nuxt:
    image: rodarte/yc-nuxt3-todo-app-dev:0.0.3
    environment:
      <<: *common-env-variables
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - ./todo-nuxt3:/node/app
      - /node/app/node_modules
