version: '3.4'

x-common-env-variables: &common-env-variables
  STAGE: development-docker

services:
  todo-nuxt:
    image: rodarte/yc-nuxt3-todo-app-dev:fa22260
    environment:
      <<: *common-env-variables
      PORT: 3000
      HMR_PORT: 3001
      HOST: 0.0.0.0
      NUXT_PUBLIC_STAGE: development-docker
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./todo-nuxt3:/node/app
      - /node/app/node_modules
