version: '3.4'

services:
  todo-nuxt:
    image: rodarte/yc-nuxt3-todo-app-prod:latest
    environment:
      MYSQL_URL_FILE_PATH: /run/secrets/todo_nuxt_mysql_url
      HASHER_ROUNDS_FILE_PATH: /run/secrets/todo_nuxt_hasher_rounds
      JWT_KEY_FILE_PATH: /run/secrets/todo_nuxt_jwt_key
    secrets:
      - todo_nuxt_mysql_url
      - todo_nuxt_hasher_rounds
      - todo_nuxt_jwt_key
secrets:
  todo_nuxt_mysql_url:
    file: ./secrets/docker/todo-nuxt3/mysql-url.secret.txt
  todo_nuxt_hasher_rounds:
    file: ./secrets/docker/todo-nuxt3/hasher-rounds.secret.txt
  todo_nuxt_jwt_key:
    file: ./secrets/docker/todo-nuxt3/jwt-key.secret.txt
